### PR TITLE
README: Remote connection improvements in libvirt 6.9.0

### PR DESCRIPTION
**Pull request by andreabolognani**

### CODE REVIEW

**Comment by roolebo** [comment]
@andreabolognani Oh, that's nice!

**Review by roolebo — APPROVED** [review]

**Comment by andreabolognani** [comment]
Ping? :)

**Review by odyssey4me — APPROVED** [review]

**Comment by andreabolognani** [comment]
ping² :)

This has been approved by two people already and it would be nice to get it merged, especially now that libvirt >= 6.9.0 is no longer very new and so it's quite likely that things will work out of the box in most cases.

**Comment by andreabolognani** [comment]
ping³

Any chance we can get this merged? libvirt 6.9.0, which includes the improvements, is a year old at this point.

Thanks!

**Comment by jeffreywildman** [comment]
Sorry for the delay, closing this PR since I've removed the FAQs. virt-viewer is the only remaining formula in this tap, hoping someone can get it merged into homebrew-core!

**Pull request closed without merging**
