### PR TITLE
Fix compilation issue

### PR DESCRIPTION
**Pull request by victorhahncastell**
(work around pointless -Werror)

### CODE REVIEW

**Comment by jeffreywildman** [comment]
Hi!  Can you tell me a bit more about the error you are seeing?

**Comment by victorhahncastell** [comment]
Hi Jeffrey,

this is the error I experience compiling with clang:

/bin/sh ../libtool  --tag=CC   --mode=link clang
-I/usr/local/Cellar/libusb/1.0.19/include/libusb-1.0  -I../usbredirhost
-I../usbredirparser -g -O2 -Wall -Werror -Wp,-D_FORTIFY_SOURCE=2
-fstack-protector --param=ssp-buffer-size=4   -o usbredirserver
usbredirserver-usbredirserver.o -L/usr/local/Cellar/libusb/1.0.19/lib
-lusb-1.0  ../usbredirhost/libusbredirhost.la
libtool: link: clang
-I/usr/local/Cellar/libusb/1.0.19/include/libusb-1.0 -I../usbredirhost
-I../usbredirparser -g -O2 -Wall -Werror -Wp,-D_FORTIFY_SOURCE=2
-fstack-protector --param=ssp-buffer-size=4 -o .libs/usbredirserver
usbredirserver-usbredirserver.o  -L/usr/local/Cellar/libusb/1.0.19/lib
../usbredirhost/.libs/libusbredirhost.dylib -lusb-1.0
/private/tmp/usbredir20150803-77837-9tq5fw/usbredir-0.7/usbredirparser/.libs/libusbredirparser.dylib
clang: error: argument unused during compilation: '-Wp,-D_FORTIFY_SOURCE=2'

Which would be a legitimate warning in my eyes but -Werror wreaks havoc
here.

**Comment by jeffreywildman** [comment]
Thanks for the reply, I'm not able to reproduce the error on my system running OSX 10.10.4 with:

    $ clang -v
    Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
    Target: x86_64-apple-darwin14.4.0
    Thread model: posix

Are you running something different?

**Comment by victorhahncastell** [comment]
Most interestingly, no. This is 10.10.4 as well, exact same clang -v output.

**Comment by jeffreywildman** [comment]
Thanks for the initial report, but until the source of the problem can be further isolated, I'm going to close the pull request.

**Pull request closed without merging**
