### PR TITLE
update virt-manager source link

### PR DESCRIPTION
**Pull request by MartinBrugnara**

### CODE REVIEW

**Comment by jeffreywildman** [comment]
Hi, I just pushed some related changes in bumping virt-manager to 1.2.0 -- they were hanging around in my local branch and should have been pushed sooner, sorry about that.

Is there a reason why fedorahosted.org is preferred over virt-manager.org?

Also, I see that your pull request includes a version bump to libvirt-python (1.2.16).  If you don't mind re-sending a pull request for that change, I'll get it merged.  Thanks!

**Comment by jeffreywildman** [comment]
libvirt-python updated to 1.2.16 in fa246686

**Comment by OrbitalSystems** [comment]
Hi I am am getting this issue
ar: internal ranlib command failed
make[2]: *** [libvirt-viewer.la] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/jeffreywildman/homebrew-virt-manager/issues

These open issues may also help:
virt-viewer: Incompatible library version libgtk-3.0.dylib https://github.com/jeffreywildman/homebrew-virt-manager/issues/141

**Comment by robinjos333** [comment]
I am also facing the same issue

```
$ virt-viewer help
dyld: Library not loaded: /usr/local/opt/gtk+3/lib/libgtk-3.0.dylib
  Referenced from: /usr/local/opt/gtk-vnc/lib/libgtk-vnc-2.0.0.dylib
  Reason: Incompatible library version: libgtk-vnc-2.0.0.dylib requires version 2407.0.0 or later, but libgtk-3.0.dylib provides version 2406.0.0
Abort trap: 6

```

**Pull request closed without merging**
